### ISSUE TITLE
Could not index class module-info.class 

### ISSUE THREAD

**Issue by Tihamer54** [ThreeTen/threeten-extra#105]
I includedd threeten-extra and threetenbp in my pom files, and the YearQuarter class seems to work, but whenever I deploy my project (mdpWarApp.war) I get the following warning:

11:53:53,041 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) JBAS015852: Could not index class module-info.class at /C:/workarea/JBossEAP/jboss-eap-6.4/standalone/deployments/mdpWebApp.war/WEB-INF/lib/threeten-extra-1.3.2.jar: java.lang.IllegalStateException: Unknown tag! pos=4 poolCount = 16
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:665) [jandex-1.2.2.Final-redhat-1.jar:1.2.2.Final-redhat-1]
	at org.jboss.jandex.Indexer.index(Indexer.java:699) [jandex-1.2.2.Final-redhat-1.jar:1.2.2.Final-redhat-1]
	at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:100) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_121]

How do I fix this?

**Comment by catull** [comment]
@Tihamer54 As already mentioned in the other issue you opened a while ago, this bug has to be fixed by the maintainers of JBoss EAP.

There is little you can do, there is nothing `threeten-extra` can do.

**Comment by jodastephen** [comment]
You could use v1.2 of `threeten-extra` as that does not have the `module-info` file.

**Comment by Tihamer54** [comment]
Thanks for your prompt answer.
EAP is also open source, so if we wanted to, we *could* fix the problem. Theoretically.
But I don't have a man-month or two to invest in doing so.  And you probably don't either.
:-(

**Comment by jodastephen** [comment]
See also [JANDEX-40](https://issues.jboss.org/browse/JANDEX-40?_sscc=t)
