### ISSUE TITLE
TestYearWeek#test_parse_CharSequenceDateTimeFormatter fails

### ISSUE THREAD

**Issue by catull** [ThreeTen/threeten-extra#45]
'mvn test' fails in master with

Running TestSuite
Configuring TestNG with: TestNG652Configurator
Tests run: 9139, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.799 sec <<< FAILURE! - in TestSuite
test_parse_CharSequenceDateTimeFormatter(org.threeten.extra.TestYearWeek)  Time elapsed: 0.014 sec  <<< FAILURE!
java.time.format.DateTimeParseException: Text 'Mon W1 2015' could not be parsed at index 2
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1947)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1849)
	at org.threeten.extra.YearWeek.parse(YearWeek.java:264)
	at org.threeten.extra.TestYearWeek.test_parse_CharSequenceDateTimeFormatter(TestYearWeek.java:617)

Is this specific to MacOS X 10.10.3 with Oracle JDK 1.8.0_45, maven 3.3.1 ?
The same effect manifests when using Azul's OpenJDK, both zulu 1.8.0_20 [1] and zulu 1.8.0_45 [2].

[1] http://cdn.azulsystems.com/zulu/2014-09-8.3-bin/zulu1.8.0_20-8.3.0.4-macosx.zip
[2] http://cdn.azulsystems.com/zulu/2015-04-8.7-bin/zulu1.8.0_45-8.7.0.5-macosx.zip

**Comment by jodastephen** [comment]
It builds locally for me. I fear you are in a better position than I am to debug the issue...

**Comment by catull** [comment]
Good catch!

On MacOS X 10.10.3, the fix works for Oracle JDK 1.8.0_45 and 1.9.0 EA b68 and Azul's OpenJDK 1.8.0_45.
