### ISSUE TITLE
Exception thrown by Math.floorDiv for version 1.3

### ISSUE THREAD

**Issue by guidomedina** [ThreeTen/threeten-extra#91]
Once we updated to the latest threeten-extra (1.3) we are getting the following exception:
```
Caused by: java.lang.NoSuchMethodError: java.lang.Math.floorDiv(JI)J
	at org.threeten.extra.chrono.JulianDate.toEpochDay(JulianDate.java:461)
	at org.threeten.extra.chrono.AbstractDate.getLong(AbstractDate.java:136)
	at org.threeten.extra.chrono.JulianDate.getLong(JulianDate.java:74)

-- End of 310-extra stack trace.

	at java.time.temporal.TemporalQueries.lambda$static$5(TemporalQueries.java:383)
	at java.time.chrono.ChronoLocalDate.query(ChronoLocalDate.java:519)
	at java.time.LocalDate.from(LocalDate.java:365)

	at de.jollyday.util.CalendarUtil.getJulianEasterSunday(CalendarUtil.java:144)
	at de.jollyday.util.CalendarUtil.getEasterSunday(CalendarUtil.java:120)
	at de.jollyday.parser.AbstractHolidayParser.getEasterSunday(AbstractHolidayParser.java:185)
	at de.jollyday.parser.impl.ChristianHolidayParser.parse(ChristianHolidayParser.java:45)
	at de.jollyday.impl.DefaultHolidayManager.parseHolidays(DefaultHolidayManager.java:153)
	at de.jollyday.impl.DefaultHolidayManager.getHolidays(DefaultHolidayManager.java:109)
	at de.jollyday.impl.DefaultHolidayManager.getHolidays(DefaultHolidayManager.java:69)
```

**Comment by jodastephen** [comment]
Released on Java 9, but Oracle's new `release` flag failed.
