### ISSUE TITLE
Libraries importing Threeten-extra failing in OSGI-Environments with a 1.8 JRE

### ISSUE THREAD

**Issue by andy-d2019** [ThreeTen/threeten-extra#97]
We use jollyday 0.5.4 in our Apache-Camel Routes on an Apache Servicemix/Karaf, this dependency requires threeten-extra 1.3.2 and thus the whole application cannot be build in an osgi/java8 environment without working around this issue.

Every library importing Threeten-Extra 1.3.2 will fail in an OSGI environment running on Java-1.8.
The issue itself seems to have been fixed a while ago #92  #94, but a fixed version is not available on maven central yet.

**Comment by kubilaykarpat** [comment]
Having the same problem with Java8.

**Comment by svendiedrichsen** [comment]
@jodastephen Do you already plan on a new fixed release for this?

**Comment by jodastephen** [comment]
v1.4 was released on August 20th

**Comment by kubilaykarpat** [comment]
Not quite sure If there is something wrong with our configuration but v1.4 and v1.5 give the same error as before:
`
[INFO] using maven-bundle-plugin v2.5.3
java.lang.ArrayIndexOutOfBoundsException: 19
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:579)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:497)
	at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:486)
	at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:476)
	at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2195)
	at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2101)
	at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:139)
	at aQute.bnd.osgi.Builder.analyze(Builder.java:352)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:618)
	at org.apache.felix.bundleplugin.ManifestPlugin.getAnalyzer(ManifestPlugin.java:213)
	at org.apache.felix.bundleplugin.ManifestPlugin.getManifest(ManifestPlugin.java:114)
	at org.apache.felix.bundleplugin.ManifestPlugin.execute(ManifestPlugin.java:69)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:294)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:285)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojoImpl(MojoExecutor.java:172)
	at org.twdata.maven.mojoexecutor.MojoExecutor$ExecutionEnvironmentM3.executeMojo(MojoExecutor.java:476)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:75)
	at com.atlassian.maven.plugins.amps.MavenGoals.generateBundleManifest(MavenGoals.java:1593)
	at com.atlassian.maven.plugins.amps.osgi.GenerateManifestMojo.execute(GenerateManifestMojo.java:65)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:353)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Manifest com.snapbytes.plugins:destech-jira-plugin:atlassian-plugin:0.29.0 : Exception: 19
[ERROR] Manifest com.snapbytes.plugins:destech-jira-plugin:atlassian-plugin:0.29.0 : Invalid class file module-info.class (java.lang.ArrayIndexOutOfBoundsException: 19)
[ERROR] Error(s) found in manifest configuration
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 min
[INFO] Finished at: 2019-03-01T09:27:08+03:00
`

Currently we are using a modified version of the v1.4 build in our project as a workaround. I will share the modification we have to use when I hear back from our colleague. Anyone still suffering from this problem?

**Comment by jodastephen** [comment]
I use v4.1.0 of the maven-bundle plugin. Maybe thats it? I don't know enough about OSGi to assist with debugging I'm afraid.
